### ISSUE TITLE
[OverDash] Impossible de remonter pendant 5 secondes

### ISSUE THREAD

**Issue by tchene** [Antoine-Pous/AnoCheat#25]
Quand je change d'onglet sur Chrome version 41.0.2272.89 m et l'overdash version  2015.03.12.1, lorsque ej reviens sur le chat, l'overdash m'empêche de remonté pendant environ 5 secondes.
Le comportement exacte serait qu'il revient continuellement en bas en permanence puisque je peux monter avec la descente instantanée de l'ascenceur

**Comment by Antoine-Pous** [comment]
Je ne parviens pas à reproduire le bogie sur cette version du script.

Je laisse le ticket ouvert et attend de voir si d'autres utilisateurs ont ce problème ou si tu es un cas isolé.

**Comment by tchene** [comment]
Bon, j'apport un peu plus de précision sur le bug, j'ai remarqué qu'il ne se produit que lorsque aucun nouveau message n'est apparu lorsqu'on reprend le focus sur l'onglet du chat, dans les autres cas il fonctionne très bien.

**Comment by Antoine-Pous** [comment]
Je ne parviens toujours pas à reproduire le bogue.
