### ISSUE TITLE
Bug à l'ouverture de chrome

### ISSUE THREAD

**Issue by MellGitHub** [Antoine-Pous/AnoCheat#31]
A l'ouverture de chrome (dernière version : Version 41.0.2272.104 (64-bit)) et à la première connexion sur le chat, le script charge au minimum 2 fois (3 parfois, et je n'ai pas encore eu plus)
Ca redevient bon si je reboot la page.

**Comment by Antoine-Pous** [comment]
Je n'ai rien trouvé concernant ce comportement, je pense que le problème viens de TamperMonkey ou de Chrome.

J'ai remonté le bogue auprès de l’éditeur de TM.

**Comment by Antoine-Pous** [comment]
Après avoir discuté du problème avec l'éditeur de TM il semblerait que ce problème soit fixé dans la version 42 de chrome :)
